Repository prography-8th-6team/android, pull requests merged in 2023-08, with the labels that each got.

#54 Feat/schedule list
  app/src/main/java/com/jerny/moiz/presentation/main/MainFragment.kt
Labels: :sparkles: enhancement

#53 일정, 장바구니 상세 화면
  app/src/main/java/com/jerny/moiz/data/network/service/ScheduleService.kt
  app/src/main/java/com/jerny/moiz/data/repository/ScheduleRepositoryImpl.kt
  app/src/main/java/com/jerny/moiz/domain/repository/ScheduleRepository.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/add/AddScheduleFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/add/AddScheduleViewModel.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/add/AddWishListFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/detail/ScheduleDetailFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/edit/EditScheduleFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/edit/EditScheduleViewModel.kt
  app/src/main/res/layout/fragment_edit_schedule.xml
  app/src/main/res/navigation/main_navigation.xml
Labels: :sparkles: enhancement, :bulb: feat

#75 이슈 처리
  app/src/main/java/com/jerny/moiz/presentation/billing/edit/EditBillingViewModel.kt
  app/src/main/java/com/jerny/moiz/presentation/createTravelList/CreateTravelListFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/add/AddScheduleViewModel.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/detail/ScheduleDetailFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/edit/EditScheduleFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/edit/EditScheduleViewModel.kt
  app/src/main/java/com/jerny/moiz/presentation/editTravelList/EditTravelListFragment.kt
  app/src/main/res/layout/fragment_add_wish_list.xml
  app/src/main/res/layout/fragment_edit_schedule.xml
  app/src/main/res/layout/fragment_journey.xml
  app/src/main/res/layout/fragment_schedule_detail.xml
  app/src/main/res/layout/item_add_schedule.xml
  app/src/main/res/layout/main_fragment.xml
Labels: :bug: bug, :sparkles: enhancement

#83 이슈 처리
  app/src/main/java/com/jerny/moiz/data/UserDataStore.kt
  app/src/main/java/com/jerny/moiz/presentation/billing/add/AddBillingFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/createTravelList/DatePickerFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/TravelDetailFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/billing/BillingAdapter.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/billing/BillingFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/ScheduleFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/WishListItemFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/add/AddScheduleFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/detail/ScheduleDetailFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/editTravelList/EditTravelListFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/login/LoginActivity.kt
  app/src/main/java/com/jerny/moiz/presentation/main/MainActivity.kt
  app/src/main/java/com/jerny/moiz/presentation/main/MainFragment.kt
  app/src/main/java/com/jerny/moiz/presentation/util/ScheduleDialog.kt
  app/src/main/res/layout/fragment_wish_list_item.xml
  app/src/main/res/layout/item_header.xml
  app/src/main/res/layout/main_fragment.xml
  app/src/main/res/navigation/main_navigation.xml
  app/src/main/res/values/themes.xml
Labels: :bug: bug, :sparkles: enhancement

#99 [Fix] 일정 리스트 이슈 수정
  app/src/main/java/com/jerny/moiz/presentation/detail/schedule/ScheduleAdapter.kt
  app/src/main/res/layout/fragment_journey.xml
Labels: :bug: bug

#100 [Fix] 이슈 처리 57, 74
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/jerny/moiz/data/repository/TravelRepositoryImpl.kt
  app/src/main/java/com/jerny/moiz/presentation/billing/BillingViewModel.kt
  app/src/main/java/com/jerny/moiz/presentation/main/MainActivity.kt
Labels: :bug: bug
